pokemons_primeira_geracao = [
    "Bulbasaur", "Ivysaur", "Venusaur", "Charmander", "Charmeleon", "Charizard",
    "Squirtle", "Wartortle", "Blastoise", "Caterpie", "Metapod", "Butterfree",
    "Weedle", "Kakuna", "Beedrill", "Pidgey", "Pidgeotto", "Pidgeot", "Rattata",
    "Raticate", "Spearow", "Fearow", "Ekans", "Arbok", "Pikachu", "Raichu",
    "Sandshrew", "Sandslash", "Nidoran♀", "Nidorina", "Nidoqueen", "Nidoran♂",
    "Nidorino", "Nidoking", "Clefairy", "Clefable", "Vulpix", "Ninetales",
    "Jigglypuff", "Wigglytuff", "Zubat", "Golbat", "Oddish", "Gloom", "Vileplume",
    "Paras", "Parasect", "Venonat", "Venomoth", "Diglett", "Dugtrio", "Meowth",
    "Persian", "Psyduck", "Golduck", "Mankey", "Primeape", "Growlithe", "Arcanine",
    "Poliwag", "Poliwhirl", "Poliwrath", "Abra", "Kadabra", "Alakazam", "Machop",
    "Machoke", "Machamp", "Bellsprout", "Weepinbell", "Victreebel", "Tentacool",
    "Tentacruel", "Geodude", "Graveler", "Golem", "Ponyta", "Rapidash", "Slowpoke",
    "Slowbro", "Magnemite", "Magneton", "Farfetch'd", "Doduo", "Dodrio", "Seel",
    "Dewgong", "Grimer", "Muk", "Shellder", "Cloyster", "Gastly", "Haunter",
    "Gengar", "Onix", "Drowzee", "Hypno", "Krabby", "Kingler", "Voltorb", "Electrode",
    "Exeggcute", "Exeggutor", "Cubone", "Marowak", "Hitmonlee", "Hitmonchan",
    "Lickitung", "Koffing", "Weezing", "Rhyhorn", "Rhydon", "Chansey", "Tangela",
    "Kangaskhan", "Horsea", "Seadra", "Goldeen", "Seaking", "Staryu", "Starmie",
    "Mr. Mime", "Scyther", "Jynx", "Electabuzz", "Magmar", "Pinsir", "Tauros",
    "Magikarp", "Gyarados", "Lapras", "Ditto", "Eevee", "Vaporeon", "Jolteon",
    "Flareon", "Porygon", "Omanyte", "Omastar", "Kabuto", "Kabutops", "Aerodactyl",
    "Snorlax", "Articuno", "Zapdos", "Moltres", "Dratini", "Dragonair", "Dragonite",
    "Mewtwo", "Mew"
]

tipos_pokemon_primeira_geracao = [
    "Planta/Venenoso", "Planta/Venenoso", "Planta/Venenoso",
    "Fogo", "Fogo", "Fogo/Voador",
    "Água", "Água", "Água",
    "Inseto", "Inseto", "Inseto/Voador",
    "Inseto/Venenoso", "Inseto/Venenoso", "Inseto/Venenoso",
    "Normal/Voador", "Normal/Voador", "Normal/Voador",
    "Normal", "Normal", "Normal/Voador",
    "Normal/Voador", "Venenoso", "Venenoso",
    "Elétrico", "Elétrico", "Terrestre",
    "Terrestre", "Venenoso", "Venenoso",
    "Venenoso/Terrestre", "Venenoso", "Venenoso",
    "Venenoso/Terrestre", "Fada", "Fada",
    "Fogo", "Fogo", "Normal/Fada",
    "Normal/Fada", "Venenoso/Voador", "Venenoso/Voador",
    "Planta/Venenoso", "Planta/Venenoso", "Planta/Venenoso",
    "Inseto/Planta", "Inseto/Planta", "Inseto/Venenoso",
    "Inseto/Venenoso", "Terrestre", "Terrestre",
    "Normal", "Normal", "Fogo",
    "Fogo", "Normal/Fada", "Normal/Fada",
    "Venenoso/Voador", "Venenoso/Voador", "Planta/Venenoso",
    "Planta/Venenoso", "Planta/Venenoso", "Inseto/Planta",
    "Inseto/Planta", "Inseto/Venenoso", "Inseto/Venenoso",
    "Terrestre", "Terrestre", "Normal",
    "Normal", "Água", "Água",
    "Lutador", "Lutador", "Fogo",
    "Fogo", "Normal", "Normal",
    "Água", "Água", "Lutador",
    "Lutador", "Fogo", "Fogo","Planta/Voador", "Planta/Voador", "Planta/Voador",
    "Elétrico", "Elétrico", "Normal",
    "Normal", "Água", "Água",
    "Lutador", "Lutador", "Normal",
    "Normal", "Água", "Água",
    "Água/Terrestre", "Água/Terrestre", "Água/Terrestre",
    "Inseto/Voador", "Inseto/Voador", "Inseto/Voador",
    "Fantasma/Venenoso", "Fantasma/Venenoso", "Elétrico",
    "Elétrico", "Normal", "Normal",
    "Psíquico", "Psíquico", "Psíquico/Voador",
    "Psíquico/Voador", "Inseto/Voador", "Inseto/Voador",
    "Terrestre", "Terrestre", "Água/Rocha",
    "Água/Rocha", "Água/Rocha", "Água/Rocha",
    "Água/Rocha", "Água/Rocha", "Planta",
    "Planta/Venenoso", "Elétrico", "Elétrico",
    "Terrestre", "Terrestre", "Terrestre",
    "Terrestre", "Terrestre", "Terrestre/Voador",
    "Inseto", "Inseto", "Água",
    "Água", "Água", "Psíquico",
    "Psíquico", "Psíquico", "Água/Gelo",
    "Água/Gelo", "Gelo/Voador", "Gelo/Voador",
    "Inseto/Voador", "Inseto/Voador", "Inseto/Voador",
    "Inseto/Voador", "Fantasma/Voador", "Fantasma/Voador",
    "Gelo/Voador", "Gelo/Voador", "Elétrico",
    "Elétrico", "Fogo", "Fogo",
    "Água", "Água", "Psíquico",
    "Psíquico", "Psíquico", "Água/Inseto",
    "Água/Inseto", "Normal", "Normal/Voador",
    "Inseto/Voador", "Inseto/Voador", "Psíquico",
    "Psíquico", "Água", "Água",
    "Planta", "Planta/Voador", "Planta/Voador",
    "Planta/Voador", "Água/Voador", "Água/Voador",
    "Pedra/Voador", "Pedra/Voador", "Elétrico",
    "Elétrico", "Lutador", "Lutador",
    "Água", "Água", "Inseto",
    "Inseto", "Água/Fantasma", "Água/Fantasma",
    "Água/Fantasma", "Água/Fantasma", "Planta/Venenoso",
    "Planta/Venenoso", "Água", "Água",
    "Água/Voador", "Água/Voador", "Água/Voador",
    "Planta/Venenoso", "Planta/Venenoso", "Inseto/Voador",
    "Inseto/Voador", "Água", "Água",
    "Pedra/Terrestre", "Pedra/Terrestre", "Pedra/Terrestre",
    "Planta/Pedra", "Planta/Pedra", "Água/Rocha",
    "Água/Rocha", "Água/Rocha", "Água/Rocha",
    "Planta/Venenoso", "Planta/Venenoso", "Água/Voador",
    "Água/Voador", "Gelo", "Gelo",
    "Gelo/Psíquico", "Gelo/Psíquico", "Elétrico",
    "Elétrico", "Elétrico", "Elétrico",
    "Normal", "Normal", "Normal",
    "Normal", "Normal", "Normal",
    "Normal", "Normal", "Normal",
    "Normal", "Normal", "Normal",
    "Normal", "Normal", "Normal",
    "Inseto/Voador", "Inseto/Voador", "Inseto/Voador",
    "Inseto/Voador", "Inseto/Voador", "Inseto/Voador",
    "Inseto/Voador", "Inseto/Voador", "Inseto/Voador",
    "Inseto/Voador", "Inseto/Voador", "Inseto/Voador",
    "Inseto/Voador", "Inseto/Voador", "Inseto/Voador",
    "Inseto/Voador", "Inseto/Voador", "Inseto/Voador",
    "Inseto/Voador", "Inseto/Voador", "Inseto/Voador",
    "Inseto/Voador", "Inseto/Voador", "Inseto/Voador",
    "Inseto/Voador", "Inseto/Voador", "Inseto/Voador",
    "Inseto/Voador", "Inseto/Voador", "Inseto/Voador",
    "Inseto/Voador", "Inseto/Voador", "Inseto/Voador",
    "Inseto/Voador", "Inseto/Voador", "Inseto/Voador",
    "Inseto/Voador", "Inseto/Voador", "Inseto/Voador",
    "Inseto/Voador", "Inseto/Voador", "Inseto/Voador",
    "Inseto/Voador", "Inseto/Voador", "Inseto/Voador"
    ]